#!/usr/bin/env bash
#
# Builds the static libraries that the release binaries of Konclude are linked against,
# i.e., GMP, libxml2, the Redland RDF libraries (raptor2, rasqal, librdf) and jemalloc, and
# copies them to the places where Konclude.pro expects them.
#
# Usage: build-static-dependencies.sh <work directory> <Konclude source directory>
#
# The optional features of the libraries that would pull in further shared libraries
# (URL retrieval via curl, XSLT for GRDDL, PCRE, libgcrypt, Berkeley DB, SQL storages,
# loadable modules) are disabled, so that the resulting binary only depends on the
# libraries of the operating system. On macOS, all libraries are built for the same
# minimum macOS version as Qt, which is 11.0 for arm64.

set -euo pipefail

if [ $# -ne 2 ]; then
	echo "Usage: $0 <work directory> <Konclude source directory>" >&2
	exit 2
fi

WORK="$(mkdir -p "$1" && cd "$1" && pwd)"
KONCLUDE="$(cd "$2" && pwd)"
SRC="$WORK/src"
LIB="$WORK/lib"
mkdir -p "$SRC" "$LIB"

JOBS="$( (getconf _NPROCESSORS_ONLN || sysctl -n hw.ncpu || echo 2) 2>/dev/null | head -1 )"

# Current versions of clang report some long-standing issues of these older C code bases,
# such as returning a pointer from a function returning int, as errors instead of warnings.
if ${CC:-cc} --version 2>/dev/null | grep -qi clang; then
	export CFLAGS="${CFLAGS:--O2} -Wno-error=int-conversion -Wno-error=implicit-function-declaration -Wno-error=incompatible-function-pointer-types -Wno-error=incompatible-pointer-types"
fi

# Otherwise the libraries would require the macOS version of the build machine, although
# Konclude itself is linked for the minimum version of Qt.
if [ "$(uname -s)" = "Darwin" ]; then
	export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-11.0}"
fi

GMP_VERSION=6.3.0
LIBXML2_VERSION=2.9.9
RAPTOR2_VERSION=2.0.15
RASQAL_VERSION=0.9.33
RASQAL_COMMIT=0c42ebc
REDLAND_VERSION=1.0.17
JEMALLOC_VERSION=5.2.1

download() {
	# download with a few retries, the source servers are occasionally slow
	curl -fsSL --retry 5 --retry-delay 10 -o "$2" "$1"
}


echo "::group::GMP $GMP_VERSION"
cd "$SRC"
download "https://ftp.gnu.org/gnu/gmp/gmp-$GMP_VERSION.tar.xz" gmp.tar.xz
tar -xJf gmp.tar.xz
cd "gmp-$GMP_VERSION"
./configure --prefix="$LIB/gmp-static" --disable-shared --enable-static --with-pic
make -j"$JOBS"
make install
echo "::endgroup::"


echo "::group::libxml2 $LIBXML2_VERSION"
cd "$SRC"
download "https://download.gnome.org/sources/libxml2/${LIBXML2_VERSION%.*}/libxml2-$LIBXML2_VERSION.tar.xz" libxml2.tar.xz
tar -xJf libxml2.tar.xz
cd "libxml2-$LIBXML2_VERSION"
./configure --prefix="$LIB/libxml2-static" --disable-shared --enable-static \
	--without-python --without-lzma --without-zlib --without-icu --without-http --without-ftp
make -j"$JOBS"
make install
echo "::endgroup::"


echo "::group::raptor2 $RAPTOR2_VERSION"
cd "$SRC"
download "http://download.librdf.org/source/raptor2-$RAPTOR2_VERSION.tar.gz" raptor2.tar.gz
tar -xzf raptor2.tar.gz
cd "raptor2-$RAPTOR2_VERSION"
# all parsers except GRDDL, which requires libxslt, and JSON, which requires yajl
./configure --prefix="$LIB/raptor2-static" --disable-shared --enable-static \
	--with-www=none --with-xml2-config="$LIB/libxml2-static/bin/xml2-config" \
	--enable-parsers="rdfxml ntriples turtle trig guess rss-tag-soup rdfa nquads"
make -j"$JOBS"
make install
echo "::endgroup::"


echo "::group::rasqal $RASQAL_VERSION (Konclude fork)"
cd "$SRC"
git clone https://github.com/konclude/rasqal.git rasqal
cd rasqal
# make sure that the fork still contains the changes Konclude relies on
git merge-base --is-ancestor "$RASQAL_COMMIT" HEAD
# the submodules libsv and libmtwist are registered with git:// URLs, which GitHub no longer serves
git -c url."https://github.com/".insteadOf="git://github.com/" submodule update --init
export RAPTOR2_CFLAGS="-I$LIB/raptor2-static/include/raptor2"
export RAPTOR2_LIBS="-L$LIB/raptor2-static/lib -lraptor2 -L$LIB/libxml2-static/lib -lxml2 -lm"
export RAPTOR_VERSION="$RAPTOR2_VERSION"
# use the given raptor version instead of asking pkg-config, which does not know the static build
sed -i.orig -e 's#RAPTOR_VERSION=`$PKG_CONFIG raptor2 --modversion 2>/dev/null`#if test -n "$RAPTOR_VERSION"; then echo "Assuming raptor version $RAPTOR_VERSION"; else RAPTOR_VERSION=`$PKG_CONFIG raptor2 --modversion 2>/dev/null`; fi#g' configure.ac
# gtk-doc is only required for the API documentation of rasqal, which is not built here, so
# the check is removed and the included gtk-doc rules are replaced with an empty file
sed -i.orig-gtkdoc -e '/^GTK_DOC_CHECK/d' configure.ac
printf 'EXTRA_DIST =\nCLEANFILES =\nDISTCLEANFILES =\nMAINTAINERCLEANFILES =\n' > gtk-doc.make
NOCONFIGURE=1 ./autogen.sh
# the lexer and the parser are not part of the repository, they are generated by flex and
# bison, for which the rules are only available in the maintainer mode
./configure --prefix="$LIB/rasqal-static" --disable-shared --enable-static --disable-gtk-doc --enable-maintainer-mode \
	--with-regex-library=posix --with-digest-library=internal --with-uuid-library=internal \
	--with-decimal=gmp --with-gmp="$LIB/gmp-static"
make -j"$JOBS"
make install
echo "::endgroup::"


echo "::group::redland $REDLAND_VERSION"
cd "$SRC"
download "http://download.librdf.org/source/redland-$REDLAND_VERSION.tar.gz" redland.tar.gz
tar -xzf redland.tar.gz
cd "redland-$REDLAND_VERSION"
export RASQAL_CFLAGS="-I$LIB/rasqal-static/include/rasqal"
export RASQAL_LIBS="-L$LIB/rasqal-static/lib -lrasqal $RAPTOR2_LIBS"
export RASQAL_VERSION
sed -i.orig -e 's#RAPTOR_VERSION=`$PKG_CONFIG raptor2 --modversion 2>/dev/null`#if test -n "$RAPTOR_VERSION"; then echo "Assuming raptor version $RAPTOR_VERSION"; else RAPTOR_VERSION=`$PKG_CONFIG raptor2 --modversion 2>/dev/null`; fi#g' configure
sed -i.orig2 -e 's#RASQAL_VERSION=`$PKG_CONFIG rasqal --modversion 2>/dev/null`#if test -n "$RASQAL_VERSION"; then echo "Assuming rasqal version $RASQAL_VERSION"; else RASQAL_VERSION=`$PKG_CONFIG rasqal --modversion 2>/dev/null`; fi#g' configure
./configure --prefix="$LIB/redland-static" --disable-shared --enable-static --disable-modular \
	--without-bdb --without-mysql --without-postgresql --without-sqlite --without-virtuoso --without-threestore
make -j"$JOBS"
make install
echo "::endgroup::"


echo "::group::jemalloc $JEMALLOC_VERSION"
cd "$SRC"
download "https://github.com/jemalloc/jemalloc/releases/download/$JEMALLOC_VERSION/jemalloc-$JEMALLOC_VERSION.tar.bz2" jemalloc.tar.bz2
tar -xjf jemalloc.tar.bz2
cd "jemalloc-$JEMALLOC_VERSION"
./configure --prefix="$LIB/jemalloc-static"
make -j"$JOBS"
make install
echo "::endgroup::"


echo "::group::Copy libraries to the Konclude sources"
RDF_DIR="$KONCLUDE/External/librdf/Linux/x64/lib/release"
JEMALLOC_DIR="$KONCLUDE/External/jemalloc/Linux/x64/lib/release"
mkdir -p "$RDF_DIR" "$JEMALLOC_DIR"
cp "$LIB/gmp-static/lib/libgmp.a" "$RDF_DIR/"
cp "$LIB/libxml2-static/lib/libxml2.a" "$RDF_DIR/"
cp "$LIB/raptor2-static/lib/libraptor2.a" "$RDF_DIR/"
cp "$LIB/rasqal-static/lib/librasqal.a" "$RDF_DIR/"
cp "$LIB/redland-static/lib/librdf.a" "$RDF_DIR/"
cp "$LIB/jemalloc-static/lib/libjemalloc.a" "$JEMALLOC_DIR/"
ls -l "$RDF_DIR" "$JEMALLOC_DIR"
echo "::endgroup::"
